---
# tasks file for roles/ansible-sbt

# echo "deb https://dl.bintray.com/sbt/debian /" | sudo tee -a /etc/apt/sources.list.d/sbt.list
# sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 642AC823
# sudo apt-get update
# sudo apt-get install sbt

- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- name: 'Install SBT package'
  become: yes
  package:
    name: sbt
    state: latest
